### ISSUE TITLE
Volcano naming conventions

### ISSUE THREAD

**Issue by jifarquharson** [BritishGeologicalSurvey/pyvolcans#11]
### Summary ###
`pyVOLCANS` documentation could do with a note on GVP naming conventions.

### Description ###
Many volcanoes have names that are more than one word, e.g. Rincon de la Vieja (Costa Rica) or St. Helens (USA): as it stands, if a user were to enter `$ pyvolcans Rincon de la Vieja` (consistent with the examples given, i.e. `$ pyvolcans Hekla`), `pyvolcans` will throw an `"unrecognized argument"` error. This can be avoided simply by wrapping the multi-word string in quotes, but as far as I can tell this isn't mentioned in the documentation. 

On a related note, volcano names crawled from the Smithsonian's GVP are often in a {Name, Prefix} format, which might not be immediately obvious for a lay end-user. A common example is "Fournaise, Piton de la." It seems that the fuzzy matching does a reasonable job of catching these in most cases; for example, "Fournaise, Piton de la" is the 9th alternative option given by `fuzzy_matching()` for "Piton de la Fournaise," and "Sawad, Harra Es-" is the 4th option given for "Harra Es-Sawad," and so on. Other systems don't fare as well (e.g. Cerro Bravo or Jabal Yar), and don't offer the correct option. While arbitrarily increasing the fuzzy limit, e.g. by including
`limit = 10 if len(volcano_name.split()) == 1 else 20`
inside the `fuzzy_matching` function helps to a degree, this workaround still doesn't capture a dozen or so systems (for example, "Bravo, Cerro" is the 42nd-best fuzzy match for "Cerro Bravo"). While writing a targeted workaround for this is probably overkill given that it is potentially a niche problem, it would be useful to have some note in the documentation regarding how to input names, the format they should be in, and where to look if your volcano appears not to be on the list, e.g. due to formatting, punctuation, or usage of a different name (one can imagine researchers looking for "Fagradalsfjall," for example, rather than "Krýsuvík-Trölladyngja"). 

### Acceptance criteria ###

- [x] Updated documentation/instructions

Ping [3649](https://github.com/openjournals/joss-reviews/issues/3649)

**Comment by PTierz** [comment]
Dear @jifarquharson,

Thank you very much for your comments and suggestions. We have carefully analysed them and, hopefully, fixed them to a satisfactory level.

Let us start with the issue observed with the `fuzzy_matching()` function. We have realised that just by substituting the function used to calculate the `scorer` value in the call to `process.extract()`, we were able to fix the issues related to the ordering of words within a given `volcano_name`. Please see commit 66305f1 (many thanks @mobiuscreek for the fix!). Therefore, in the current version of PyVOLCANS ([v1.2.2]( https://github.com/BritishGeologicalSurvey/pyvolcans/releases/tag/v1.2.2)), all the described searches provide the appropriate `volcano_name` as the first entry of the `fuzzy_matching()` output: `$ pyvolcans “Piton de la Fournaise”`, `$ pyvolcans “Harra Es-Sawad”`, `$ pyvolcans “Jabal Yar”`, and `$ pyvolcans “Cerro Bravo”`. The last example is a complicated one, as 17 volcanoes in the latest [Holocene Volcano List]( https://volcano.si.edu/list_volcano_holocene.cfm) include the word “Cerro” in their volcano names. We have performed further checks using: `$ pyvolcans "Cerro Tujle"`, `$ pyvolcans "Cerro del Azufre"`, and `$ pyvolcans "Cerro el Ciguatepe"`, and, in all cases, the first returned suggestion corresponds with the `volcano_name` of the target volcano. Many thanks.

Regarding the use of quotation marks for any `volcano_name` that is composed of more than one word, very many thanks for pointing it out – we had not thought of including these instructions. We have now included a few sentences in the main [README.md file]( https://github.com/BritishGeologicalSurvey/pyvolcans/blob/main/README.md) that explain this matter and how to properly run `pyvolcans` in this kind of situations.

Similarly, we have included some explanations about possible synonyms and subfeatures linked with the volcanic systems listed in the GVP database, and have suggested a possible workaround to this problem.

We sincerely hope that the improvements incorporated in the latest version of PyVOLCANS will be satisfactory, and this can close the current open issue. Very many thanks.

In any case, I will leave the acceptance criteria unchecked, so you can have the chance to double-check what I have described above. Could I kindly ask you (after your checks) to check the box and close the issue if you consider that our changes have resolved the issue?

Thank you very much again for your reviews and suggestions.

Best regards,
Pablo (on behalf of the co-authors)

**Comment by jifarquharson** [comment]
Hi @PTierz, 

Thanks for digging into this. I gave [v1.2.2](https://github.com/BritishGeologicalSurvey/pyvolcans/releases/tag/v1.2.2) a test-drive, and the one-line fix at [`66305f1`](https://github.com/BritishGeologicalSurvey/pyvolcans/commit/66305f13dc8b457fadc463e25aea43b26411801f) works great! Combined with the updates to the README, the peculiarities of the naming convention are now much easier to navigate. Happy to close this issue.

Best Regards,
Jamie
