### ISSUE TITLE
Update required dependency to thefuzz (https://github.com/seatgeek/thefuzz)

### ISSUE THREAD

**Issue by maxrjones** [BritishGeologicalSurvey/pyvolcans#14]
One of your required dependencies has been deprecated. I recommend updating the dependency to the new repository https://github.com/seatgeek/thefuzz (`pip install thefuzz`). Please see closed issues in the deprecated repository for reasoning.

re: https://github.com/openjournals/joss-reviews/issues/3649

**Comment by mobiuscreek** [comment]
Hi @meghanrjones , thank you for noticing this and making this issue. I've made the changes in #15. Can you please let us know if you are happy with it so we can merge ?

**Comment by maxrjones** [comment]
> Hi @meghanrjones , thank you for noticing this and making this issue. I've made the changes in #15. Can you please let us know if you are happy with it so we can merge ?

Looks good, thanks!

**Comment by mobiuscreek** [comment]
Thank you, #15 is now merged.
