### ISSUE TITLE
Forbid the use of negative values for the criteria weights

### ISSUE THREAD

**Issue by PTierz** [BritishGeologicalSurvey/pyvolcans#6]
### Summary

In version v1.0.3 of `PyVOLCANS`, the user could introduce negative values for some of the weights for the volcanological criteria, and the code ran as normal, without raising an exception, provided that the sum of weights was 1 (with a precision error of `1e-9`).

### Fix

The issue has been addressed in commit d046c44, within the `plot-bars` branch (to be merged into `main`), by adding a check for negative values of the criteria weights inside the `set_weights_from_args()` function.

### Acceptance criteria

+ [x] `pyvolcans Telica -Ts 0.3 -G 0.1 -M 0.1 -Sz 0.3 -St -0.2 -w` throws the following error message `PyVOLCANS: Some criterion weights are negative values! Please revise your weighting scheme.`, and terminates execution of the program.
+ [x] `pyvolcans Telica -Ts 0.3 -G 0.1 -M 0.1 -St 0.3 -St -0.2 -w` throws the following error message `PyVOLCANS: Some criterion weights are duplicated! Please revise your weighting scheme.`, and terminates execution of the program.
+ [x] `pyvolcans Telica -Ts 0.3 -G 0.1 -M 0.1 -Sz 0.3 -St 0.2 -w` or `pyvolcans Telica` run the program as expected.
+ [x] `pyvolcans Telica -Ts 0.3 -G 0.1 -M 0.1 -Sz 0.5 -St -0 -w` or `pyvolcans Telica -Ts 0.3 -G 0.1 -M 0.1 -Sz 0.5 -St 0 -w` run the program as expected and produce the same output, including the generated csv file.

**Comment by volcan01010** [comment]
Closed by #5.
