### ISSUE TITLE
Prepare paper for JOSS submission

### ISSUE THREAD

**Issue by volcan01010** [BritishGeologicalSurvey/pyvolcans#7]
### Summary

As PyVOLCANs authors we all want to be happy with the JOSS manuscript so that we can submit it.

### Description

This issue is a placeholder where we can discuss changes to the JOSS manuscript prior to submission.  The manuscript is stored in the `papers` folder on the [JOSS_paper branch](https://github.com/BritishGeologicalSurvey/pyvolcans/tree/JOSS_paper/paper).

### Acceptance criteria

+ [x] Pablo is happy with text
+ [x] Vyron is happy with text
+ [x] John is happy with text

**Comment by volcan01010** [comment]
@PTierz @mobiuscreek - I have pushed my edits of the manuscript up here for us to finalise before submitting to JOSS.

**Comment by mobiuscreek** [comment]
Thanks @volcan01010.  Provided that @PTierz can check some of the references without DOIs, I am happy with it.

**Comment by PTierz** [comment]
Paper was submitted yesterday evening. Very many thanks @mobiuscreek, @volcan01010 for all your work and support!! :)
